### ISSUE TITLE
WindowsError: [Error 126] The specified module could not be found

### ISSUE THREAD

**Issue by sonichorsee** [tejado/pokemongo-api-demo#188] opened 2016-08-07 06:54 UTC
Running "pokecli.py" on 64bit windows:

2016-08-06 23:50:41,299 [    pgoapi] [ INFO] pgoapi v1.1.7 - Copyright (c) 2016 tjado https://github.com/tejado
2016-08-06 23:50:42,348 [ utilities] [ INFO] Location for '33.761606, -118.193041' found: 330 S Pine Ave, Long Beach, CA 90802, USA
2016-08-06 23:50:42,348 [ utilities] [ INFO] Coordinates (lat/long/alt) for location: 33.761973 -118.1934017 0.0
2016-08-06 23:50:42,348 [auth_google] [ INFO] Google User Login for: xxxx@gmail.com
2016-08-06 23:50:42,950 [auth_google] [ INFO] Google User Login successful.
2016-08-06 23:50:42,950 [auth_google] [ INFO] Request Google Access Token...
2016-08-06 23:50:43,329 [auth_google] [ INFO] Google Access Token successfully received.
2016-08-06 23:50:43,361 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-06 23:50:43,361 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
Traceback (most recent call last):
  File "C:\Users\xxxx\Pokemon\pgoapi-master\pokecli.py", line 133, in <module>
    main()
  File "C:\Users\xxxx\Pokemon\pgoapi-master\pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "C:\Users\xxxx\Pokemon\pgoapi-master\pgoapi\pgoapi.py", line 122, in function
    return request.call()
  File "C:\Users\xxxx\Pokemon\pgoapi-master\pgoapi\pgoapi.py", line 210, in call
    request.activate_signature(lib_path)
  File "C:\Users\xxxx\Pokemon\pgoapi-master\pgoapi\rpc_api.py", line 85, in activate_signature
    self._signature_lib = ctypes.cdll.LoadLibrary(lib_path)
  File "C:\Python27\lib\ctypes__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes__init__.py", line 362, in **init**
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by elliottcarlson** [comment] 2016-08-07 19:56
Duplicate of #197

**Closed as completed** 2016-08-07 20:16 UTC
