### ISSUE TITLE
get_map_objects does not return pokestops, gyms, or pokemon.

### ISSUE THREAD

**Issue by ghost** [tejado/pokemongo-api-demo#200] opened 2016-08-07 21:31 UTC
When I request get_map_objects() I just returns many current_timestamp_ms and s2_cell_id and nothing listed in the title. Any help would be great, heading off right now to a birthday party so wont be able to reply for awhile.

Code: https://gyazo.com/75f83e378ad0b9ae372eebf5007a17cf

**Comment by elliottcarlson** [comment] 2016-08-07 21:35
Duplicate of #191 

You will need to use the new repo code that adds the signature to the request. Either use the other repo for the time being, or use the pull request that is open on this one (https://github.com/tejado/pgoapi/pull/182) or wait until the updates have been officially merged.

**Comment by ghost** [comment] 2016-08-07 21:46
Used repo with updates still get the same thing @elliottcarlson

**Comment by elliottcarlson** [comment] 2016-08-07 21:48
Your code isn't using `api.activate_signature()` with a reference to the signature library.

See https://github.com/keyphact/pgoapi/blob/master/pokecli.py#L123

**Closed as completed** 2016-08-08 04:03 UTC
